#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets [@]user")
    
    user = sys.argv[1]
    timeline = get_user_timeline(user)
    
    if timeline == None:
        sys.exit("Failed to get timeline for user={}".format(user))
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    for tweet in timeline:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(":) {}".format(tweet), "green"))
        elif score < 0.0:
            print(colored(":( {}".format(tweet), "red"))
        else:
            print(colored(":| {}".format(tweet), "yellow"))

if __name__ == "__main__":
    main()